### PR TITLE
Rename ReactiveOps to Fairwinds

### PR DESCRIPTION
**Pull request by bobby-brennan**
Remaining mentions: 
```

```

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Any idea why CI failed?

**Comment by endzyme** [comment]
Agreed (@bobby-brennan). The error in the CI isn't quite clear as to the condition to fix
```
#!/bin/bash -eo pipefail
make test TF_PLATFORM=linux
Temp directory: /tmp/tmp.k3kSBA0Rpj
498a499
>       owner_id:                         <computed>
501a503
>       requester_managed:                <computed>
Makefile:17: recipe for target 'test' failed
make: *** [test] Error 1
Exited with code 2
```

**Comment by mjhuber** [comment]
unfortunately I'm not too familiar with the testing yet myself

**Comment by bobby-brennan** [comment]
Sadly the test seems to hang for me locally...seems to be waiting for an `aws_access_key`?

**Comment by bobby-brennan** [comment]
@davekonopka looks like you authored the Makefile - any tips on fixing the tests?

**Comment by davekonopka** [comment]
@bobby-brennan It's up for debate how value these tests provide. They run a `terraform plan` against a few sets of variable inputs and do a diff on results against expected output stored in files. I can add and push updated fixture files to this PR branch to include recent module changes. `make fixtures` regenerates the plan output files.

**Comment by bobby-brennan** [comment]
👍 sounds good to me, thanks!

**Comment by bobby-brennan** [comment]
Thanks Dave!

**Pull request merged**
