### PR TITLE
0.12 migration

### PR DESCRIPTION
**Pull request by bambash**
This PR upgrades the root module to support Terraform 0.12. The `single-cluster` modules remain untouched. This was tested a few different ways on existing 0.11 VPCs. All existing inputs and outputs are untouched. These changes should be compatible with existing infrastructure created using 0.11.

### CODE REVIEW

**Comment by endzyme** [comment]
Thanks so much for getting this ball rolling!! :tada: 

I'd be curious to understand more of the user experience when trying to upgrade a repo to tf 0.12. Are there other gotchas that need to be addressed like minimum version of provider needed? Happy to take this offline too and also do my own research :)

**Comment by mjhuber** [comment]
I tested .11 => .12 migration and it works great - thanks @bambash !  Any plans to update the `single-cluster` module?

**Comment by bambash** [comment]
I haven't tested the single-cluster module quite yet as we don't have many things using it. Getting it on 0.12 shouldn't be too bad. If we want to wait to tag/merge, I can update this branch and test it out.

**Comment by mjhuber** [comment]
makes sense to me to merge right now and we can wait to tag until the `single-cluster` module .  Thoughts?

**Comment by bambash** [comment]
That works for me too. Any ideas on the tag? `v5.0.0`?

**Comment by mjhuber** [comment]
> That works for me too. Any ideas on the tag? `v5.0.0`?

Sounds appropriate to me, and from ~v5.0.0 it will require terraform 0.12

**Pull request merged**
